package admin

// The three enumerations the events family validates its query parameters
// against, and the event types a realm enables by default.
//
// Every name here was read off `GET /admin/serverinfo`'s `enums` block on a
// live 26.7.1 rather than transcribed from the documentation, and the default
// list off `GET /admin/realms/master/events/config`. They are separate data
// because they are separate measurements: the enumeration is what the server
// will *accept*, and the default list is what a realm *enables*, and the two
// differ by 29 names.

// eventTypeNames is the `eventType` enumeration, 132 names.
//
// An unknown one is a **500** on `GET .../events?type=`, not a 400 - Keycloak's
// own defect, reproduced - and the comparison is case-sensitive: `type=login`
// is the 500 where `type=LOGIN` is a 200.
var eventTypeNames = map[string]bool{}

// eventTypeList is the raw enumeration, in the order `serverinfo` reports it.
// It exists to build the map above and to make the count assertable.
var eventTypeList = []string{
	"AUTHREQID_TO_TOKEN", "AUTHREQID_TO_TOKEN_ERROR", "CLIENT_DELETE",
	"CLIENT_DELETE_ERROR", "CLIENT_INFO", "CLIENT_INFO_ERROR",
	"CLIENT_INITIATED_ACCOUNT_LINKING",
	"CLIENT_INITIATED_ACCOUNT_LINKING_ERROR", "CLIENT_LOGIN",
	"CLIENT_LOGIN_ERROR", "CLIENT_REGISTER", "CLIENT_REGISTER_ERROR",
	"CLIENT_UPDATE", "CLIENT_UPDATE_ERROR", "CODE_TO_TOKEN",
	"CODE_TO_TOKEN_ERROR", "CUSTOM_REQUIRED_ACTION",
	"CUSTOM_REQUIRED_ACTION_ERROR", "DELETE_ACCOUNT", "DELETE_ACCOUNT_ERROR",
	"EXECUTE_ACTIONS", "EXECUTE_ACTIONS_ERROR", "EXECUTE_ACTION_TOKEN",
	"EXECUTE_ACTION_TOKEN_ERROR", "FEDERATED_IDENTITY_LINK",
	"FEDERATED_IDENTITY_LINK_ERROR", "FEDERATED_IDENTITY_OVERRIDE_LINK",
	"FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR", "GRANT_CONSENT",
	"GRANT_CONSENT_ERROR", "IDENTITY_PROVIDER_FIRST_LOGIN",
	"IDENTITY_PROVIDER_FIRST_LOGIN_ERROR", "IDENTITY_PROVIDER_LINK_ACCOUNT",
	"IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR", "IDENTITY_PROVIDER_LOGIN",
	"IDENTITY_PROVIDER_LOGIN_ERROR", "IDENTITY_PROVIDER_POST_LOGIN",
	"IDENTITY_PROVIDER_POST_LOGIN_ERROR", "IDENTITY_PROVIDER_RESPONSE",
	"IDENTITY_PROVIDER_RESPONSE_ERROR", "IDENTITY_PROVIDER_RETRIEVE_TOKEN",
	"IDENTITY_PROVIDER_RETRIEVE_TOKEN_ERROR", "IMPERSONATE",
	"IMPERSONATE_ERROR", "INTROSPECT_TOKEN", "INTROSPECT_TOKEN_ERROR",
	"INVALID_SIGNATURE", "INVALID_SIGNATURE_ERROR", "INVITE_ORG",
	"INVITE_ORG_ERROR", "JWT_AUTHORIZATION_GRANT",
	"JWT_AUTHORIZATION_GRANT_ERROR", "LOGIN", "LOGIN_ERROR", "LOGOUT",
	"LOGOUT_ERROR", "OAUTH2_DEVICE_AUTH", "OAUTH2_DEVICE_AUTH_ERROR",
	"OAUTH2_DEVICE_CODE_TO_TOKEN", "OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR",
	"OAUTH2_DEVICE_VERIFY_USER_CODE", "OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR",
	"OAUTH2_EXTENSION_GRANT", "OAUTH2_EXTENSION_GRANT_ERROR",
	"PERMISSION_TOKEN", "PERMISSION_TOKEN_ERROR",
	"PUSHED_AUTHORIZATION_REQUEST", "PUSHED_AUTHORIZATION_REQUEST_ERROR",
	"REFRESH_TOKEN", "REFRESH_TOKEN_ERROR", "REGISTER", "REGISTER_ERROR",
	"REGISTER_NODE", "REGISTER_NODE_ERROR", "REMOVE_CREDENTIAL",
	"REMOVE_CREDENTIAL_ERROR", "REMOVE_FEDERATED_IDENTITY",
	"REMOVE_FEDERATED_IDENTITY_ERROR", "REMOVE_TOTP", "REMOVE_TOTP_ERROR",
	"RESET_PASSWORD", "RESET_PASSWORD_ERROR", "RESTART_AUTHENTICATION",
	"RESTART_AUTHENTICATION_ERROR", "REVOKE_GRANT", "REVOKE_GRANT_ERROR",
	"SEND_IDENTITY_PROVIDER_LINK", "SEND_IDENTITY_PROVIDER_LINK_ERROR",
	"SEND_RESET_PASSWORD", "SEND_RESET_PASSWORD_ERROR", "SEND_VERIFY_EMAIL",
	"SEND_VERIFY_EMAIL_ERROR", "TOKEN_EXCHANGE", "TOKEN_EXCHANGE_ERROR",
	"UNREGISTER_NODE", "UNREGISTER_NODE_ERROR", "UPDATE_CONSENT",
	"UPDATE_CONSENT_ERROR", "UPDATE_CREDENTIAL", "UPDATE_CREDENTIAL_ERROR",
	"UPDATE_EMAIL", "UPDATE_EMAIL_ERROR", "UPDATE_PASSWORD",
	"UPDATE_PASSWORD_ERROR", "UPDATE_PROFILE", "UPDATE_PROFILE_ERROR",
	"UPDATE_TOTP", "UPDATE_TOTP_ERROR", "USER_DISABLED_BY_PERMANENT_LOCKOUT",
	"USER_DISABLED_BY_PERMANENT_LOCKOUT_ERROR",
	"USER_DISABLED_BY_TEMPORARY_LOCKOUT",
	"USER_DISABLED_BY_TEMPORARY_LOCKOUT_ERROR", "USER_INFO_REQUEST",
	"USER_INFO_REQUEST_ERROR", "USER_SESSION_DELETED",
	"USER_SESSION_DELETED_ERROR", "VALIDATE_ACCESS_TOKEN",
	"VALIDATE_ACCESS_TOKEN_ERROR", "VERIFIABLE_CREDENTIAL_CREATE_OFFER",
	"VERIFIABLE_CREDENTIAL_CREATE_OFFER_ERROR",
	"VERIFIABLE_CREDENTIAL_NONCE_REQUEST",
	"VERIFIABLE_CREDENTIAL_NONCE_REQUEST_ERROR",
	"VERIFIABLE_CREDENTIAL_OFFER_REQUEST",
	"VERIFIABLE_CREDENTIAL_OFFER_REQUEST_ERROR",
	"VERIFIABLE_CREDENTIAL_PRE_AUTHORIZED_GRANT",
	"VERIFIABLE_CREDENTIAL_PRE_AUTHORIZED_GRANT_ERROR",
	"VERIFIABLE_CREDENTIAL_REQUEST", "VERIFIABLE_CREDENTIAL_REQUEST_ERROR",
	"VERIFY_EMAIL", "VERIFY_EMAIL_ERROR", "VERIFY_PROFILE",
	"VERIFY_PROFILE_ERROR",
}

// operationTypeNames is the `operationType` enumeration, and it really is only
// four. `ACTION` is the one that is not a verb: `PUT .../reset-password` and
// `POST .../logout` both record one where other PUTs record `UPDATE`.
var operationTypeNames = map[string]bool{}

var operationTypeList = []string{
	"ACTION", "CREATE", "DELETE", "UPDATE",
}

// resourceTypeNames is the `resourceType` enumeration, 39 names. Three of them
// name a relation that appears nowhere in the URL of the write that produces
// them - `GROUP_MEMBERSHIP`, `REALM_ROLE_MAPPING`, `CLIENT_SCOPE_CLIENT_MAPPING`
// - which is half of why this project does not emit admin events. See F162.
var resourceTypeNames = map[string]bool{}

var resourceTypeList = []string{
	"AUTHENTICATOR_CONFIG", "AUTHORIZATION_POLICY", "AUTHORIZATION_RESOURCE",
	"AUTHORIZATION_RESOURCE_SERVER", "AUTHORIZATION_SCOPE", "AUTH_EXECUTION",
	"AUTH_EXECUTION_FLOW", "AUTH_FLOW", "CLIENT",
	"CLIENT_INITIAL_ACCESS_MODEL", "CLIENT_ROLE", "CLIENT_ROLE_MAPPING",
	"CLIENT_SCOPE", "CLIENT_SCOPE_CLIENT_MAPPING", "CLIENT_SCOPE_MAPPING",
	"CLUSTER_NODE", "COMPONENT", "CUSTOM", "GROUP", "GROUP_MEMBERSHIP",
	"IDENTITY_PROVIDER", "IDENTITY_PROVIDER_MAPPER", "ORGANIZATION",
	"ORGANIZATION_GROUP", "ORGANIZATION_GROUP_MEMBERSHIP",
	"ORGANIZATION_MEMBERSHIP", "PROTOCOL_MAPPER", "REALM", "REALM_ROLE",
	"REALM_ROLE_MAPPING", "REALM_SCOPE_MAPPING", "REQUIRED_ACTION",
	"REQUIRED_ACTION_CONFIG", "USER", "USER_FEDERATION_MAPPER",
	"USER_FEDERATION_PROVIDER", "USER_LOGIN_FAILURE", "USER_PROFILE",
	"USER_SESSION",
}

// defaultEnabledEventTypes is what `GET .../events/config` serves for
// `enabledEventTypes` when the realm has none stored, which is every realm a
// default install has. 103 of the 132, in the enumeration's **declaration** order
// rather than the sorted order `serverinfo` reports - byte for byte the list a
// fresh `master` and a fresh created realm both answer.
//
// The other 29 exist and are simply not saved by default. A realm that stores
// an explicit list serves that list instead, and the realm representation one
// path segment away serves `[]` for the same stored state - the one cell where
// the two views of this state disagree.
var defaultEnabledEventTypes = []string{
	"LOGIN", "LOGIN_ERROR", "REGISTER", "REGISTER_ERROR", "LOGOUT",
	"LOGOUT_ERROR", "CODE_TO_TOKEN", "CODE_TO_TOKEN_ERROR", "CLIENT_LOGIN",
	"CLIENT_LOGIN_ERROR", "FEDERATED_IDENTITY_LINK",
	"FEDERATED_IDENTITY_LINK_ERROR", "REMOVE_FEDERATED_IDENTITY",
	"REMOVE_FEDERATED_IDENTITY_ERROR", "UPDATE_EMAIL", "UPDATE_EMAIL_ERROR",
	"UPDATE_PROFILE", "UPDATE_PROFILE_ERROR", "UPDATE_PASSWORD",
	"UPDATE_PASSWORD_ERROR", "UPDATE_TOTP", "UPDATE_TOTP_ERROR",
	"VERIFY_EMAIL", "VERIFY_EMAIL_ERROR", "VERIFY_PROFILE",
	"VERIFY_PROFILE_ERROR", "REMOVE_TOTP", "REMOVE_TOTP_ERROR",
	"GRANT_CONSENT", "GRANT_CONSENT_ERROR", "UPDATE_CONSENT",
	"UPDATE_CONSENT_ERROR", "REVOKE_GRANT", "REVOKE_GRANT_ERROR",
	"SEND_VERIFY_EMAIL", "SEND_VERIFY_EMAIL_ERROR", "SEND_RESET_PASSWORD",
	"SEND_RESET_PASSWORD_ERROR", "SEND_IDENTITY_PROVIDER_LINK",
	"SEND_IDENTITY_PROVIDER_LINK_ERROR", "RESET_PASSWORD",
	"RESET_PASSWORD_ERROR", "RESTART_AUTHENTICATION",
	"RESTART_AUTHENTICATION_ERROR", "IDENTITY_PROVIDER_LINK_ACCOUNT",
	"IDENTITY_PROVIDER_LINK_ACCOUNT_ERROR", "IDENTITY_PROVIDER_LOGIN",
	"IDENTITY_PROVIDER_LOGIN_ERROR", "IDENTITY_PROVIDER_FIRST_LOGIN",
	"IDENTITY_PROVIDER_FIRST_LOGIN_ERROR", "IDENTITY_PROVIDER_POST_LOGIN",
	"IDENTITY_PROVIDER_POST_LOGIN_ERROR", "IMPERSONATE", "IMPERSONATE_ERROR",
	"CUSTOM_REQUIRED_ACTION", "CUSTOM_REQUIRED_ACTION_ERROR",
	"EXECUTE_ACTIONS", "EXECUTE_ACTIONS_ERROR", "EXECUTE_ACTION_TOKEN",
	"EXECUTE_ACTION_TOKEN_ERROR", "CLIENT_REGISTER", "CLIENT_REGISTER_ERROR",
	"CLIENT_UPDATE", "CLIENT_UPDATE_ERROR", "CLIENT_DELETE",
	"CLIENT_DELETE_ERROR", "CLIENT_INITIATED_ACCOUNT_LINKING",
	"CLIENT_INITIATED_ACCOUNT_LINKING_ERROR", "TOKEN_EXCHANGE",
	"TOKEN_EXCHANGE_ERROR", "OAUTH2_DEVICE_AUTH", "OAUTH2_DEVICE_AUTH_ERROR",
	"OAUTH2_DEVICE_VERIFY_USER_CODE", "OAUTH2_DEVICE_VERIFY_USER_CODE_ERROR",
	"OAUTH2_DEVICE_CODE_TO_TOKEN", "OAUTH2_DEVICE_CODE_TO_TOKEN_ERROR",
	"AUTHREQID_TO_TOKEN", "AUTHREQID_TO_TOKEN_ERROR", "PERMISSION_TOKEN",
	"DELETE_ACCOUNT", "DELETE_ACCOUNT_ERROR",
	"USER_DISABLED_BY_PERMANENT_LOCKOUT",
	"USER_DISABLED_BY_TEMPORARY_LOCKOUT", "OAUTH2_EXTENSION_GRANT",
	"OAUTH2_EXTENSION_GRANT_ERROR", "FEDERATED_IDENTITY_OVERRIDE_LINK",
	"FEDERATED_IDENTITY_OVERRIDE_LINK_ERROR", "UPDATE_CREDENTIAL",
	"UPDATE_CREDENTIAL_ERROR", "REMOVE_CREDENTIAL", "REMOVE_CREDENTIAL_ERROR",
	"INVITE_ORG", "INVITE_ORG_ERROR", "VERIFIABLE_CREDENTIAL_REQUEST",
	"VERIFIABLE_CREDENTIAL_REQUEST_ERROR",
	"VERIFIABLE_CREDENTIAL_OFFER_REQUEST",
	"VERIFIABLE_CREDENTIAL_OFFER_REQUEST_ERROR",
	"VERIFIABLE_CREDENTIAL_CREATE_OFFER",
	"VERIFIABLE_CREDENTIAL_CREATE_OFFER_ERROR",
	"VERIFIABLE_CREDENTIAL_PRE_AUTHORIZED_GRANT",
	"VERIFIABLE_CREDENTIAL_PRE_AUTHORIZED_GRANT_ERROR",
	"JWT_AUTHORIZATION_GRANT", "JWT_AUTHORIZATION_GRANT_ERROR",
}

func init() {
	for _, n := range eventTypeList {
		eventTypeNames[n] = true
	}
	for _, n := range operationTypeList {
		operationTypeNames[n] = true
	}
	for _, n := range resourceTypeList {
		resourceTypeNames[n] = true
	}
}
